# Generated by Django 4.1.3 on 2022-11-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_dbc', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_Car')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('date_start_manuf', models.DateField(verbose_name='Год начала выпуска')),
                ('date_end_manuf', models.DateField(verbose_name='Год окончания выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_dbc', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_Country')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Manuf',
            fields=[
                ('id_dbc', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_Manuf')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('manuf_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appCar.country')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_dbc', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_Comment')),
                ('email', models.EmailField(max_length=50, verbose_name='Email автора')),
                ('date_publ', models.DateField(auto_now_add=True, max_length=150, verbose_name='Дата создания')),
                ('text_comment', models.TextField(max_length=150, verbose_name='Текст комментария')),
                ('comment_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appCar.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_manuf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appCar.manuf'),
        ),
    ]
