# Generated by Django 4.1.3 on 2022-11-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='date_end_manuf',
            new_name='car_date_end_manuf',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date_start_manuf',
            new_name='car_date_start_manuf',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='id_dbc',
            new_name='id_car',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_publ',
            new_name='comment_date_publ',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='comment_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='comment_text_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='id_dbc',
            new_name='id_comment',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='id_dbc',
            new_name='id_country',
        ),
        migrations.RenameField(
            model_name='manuf',
            old_name='id_dbc',
            new_name='id_manuf',
        ),
        migrations.RenameField(
            model_name='manuf',
            old_name='name',
            new_name='manuf_name',
        ),
    ]
