# Generated by Django 4.1.3 on 2022-11-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCar', '0002_rename_date_end_manuf_car_car_date_end_manuf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_manuf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appCar.manuf', to_field='manuf_name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appCar.car', to_field='car_name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='manuf',
            name='manuf_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appCar.country', to_field='country_name'),
        ),
        migrations.AlterField(
            model_name='manuf',
            name='manuf_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
    ]
